pipeline {
    agent { label 'htis-stage' }

    environment {
        REPO_URI = 'git@github.com:hashtechinfosystems/htis-web-cicd.git'
        REPO_NAME = 'htis-web-cicd'
        REPO_BRANCH = 'main'
        REPO_CREDS_ID = 'htis-git-ssh-cred'
        IMAGE_NAME = 'htcl/htis-web-app'
        IMAGE_TAG = 'v1.0.0'
        CONTAINER_NAME = 'htis-webapp'
    }

    stages {
        stage('Checkout') {
            steps {
                sh 'echo "Checking out $REPO_NAME"'
                git url: env.REPO_URI, branch: env.REPO_BRANCH, credentialsId: env.REPO_CREDS_ID
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'ls -la'
                sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
                }
        }
        stage('Docker Hub Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-cred', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                sh 'ls -la'
                sh 'docker push $IMAGE_NAME:$IMAGE_TAG'
            }
        }

        stage('Remove Local Image') {
            steps {
                sh 'ls -la'
                sh 'docker rmi $IMAGE_NAME:$IMAGE_TAG || true'
            }
        }

        stage('Deploy Container') {
            steps {
                sh 'ls -la'
                sh '''
                    docker rm -f $CONTAINER_NAME || true
                    docker pull $IMAGE_NAME:$IMAGE_TAG
                    docker run -d --name $CONTAINER_NAME -p 9080:80 $IMAGE_NAME:$IMAGE_TAG
                '''
            }
        }

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
    }

    post {
        always {
            sh 'docker logout'
        }
    }
}
